import assert from 'node:assert/strict'
import test from 'node:test'
import { dispatchDriverOfferChannels, sendResendOfferEmail, sendTwilioOfferSms } from './driverOfferChannels.js'

function db(seed = []) {
  const rows = seed.map((x) => ({ ...x }))
  const from = () => { const f = []; let update; const match = (r) => f.every(({ key, value, op }) => op === 'gte' ? new Date(r[key]) >= new Date(value) : r[key] === value); const api = { select() { return api }, eq(key, value) { f.push({ key, value }); return api }, gte(key, value) { f.push({ key, value, op: 'gte' }); return api }, insert(row) { api.row = row; return api }, update(row) { update = row; return api }, then(resolve) { if (api.row) { if (rows.some((r) => ['trip_id', 'driver_id', 'offer_marker', 'channel'].every((k) => r[k] === api.row[k]))) return resolve({ error: { message: 'duplicate' } }); rows.push({ ...api.row }); return resolve({ data: null, error: null }) } if (update) { for (const r of rows.filter(match)) Object.assign(r, update); return resolve({ data: null, error: null }) } resolve({ data: rows.filter(match), error: null }) } }; return api }
  return { sb: { from }, rows }
}
const base = (sb, extra = {}) => ({ sb, tripId: 'trip', driverId: 'driver', offerMarker: 'offer', phone: '+18645550100', email: 'driver@example.com', prefs: {}, copy: { title: 'New ride request', body: 'A → B' }, now: new Date('2026-10-05T12:00:00Z'), ...extra })
const KEYS = ['DRIVER_OFFER_ALERT_SMS', 'DRIVER_OFFER_ALERT_EMAIL', 'TWILIO_ACCOUNT_SID', 'TWILIO_AUTH_TOKEN', 'TWILIO_FROM_NUMBER', 'RESEND_API_KEY', 'RESEND_FROM', 'DRIVER_OFFER_ALERT_SMS_MAX_PER_HOUR']
function env(values) { for (const key of KEYS) delete process.env[key]; Object.assign(process.env, values) }

test('offer channels: flags off make no provider calls', async () => { env({}); const store = db(); let calls = 0; const out = await dispatchDriverOfferChannels(base(store.sb), { sendSms: async () => calls++, sendEmail: async () => calls++ }); assert.equal(calls, 0); assert.equal(out.sms.reason, 'live_send_disabled'); assert.equal(out.email.reason, 'live_send_disabled') })
test('offer channels send injected Twilio and Resend senders once', async () => { env({ DRIVER_OFFER_ALERT_SMS: 'send', DRIVER_OFFER_ALERT_EMAIL: 'send', TWILIO_ACCOUNT_SID: 'a', TWILIO_AUTH_TOKEN: 'b', TWILIO_FROM_NUMBER: '+1', RESEND_API_KEY: 'key', RESEND_FROM: 'x@y.com' }); const store = db(); const calls = []; const deps = { sendSms: async (p) => { calls.push(['sms', p]); return { id: 'SM1' } }, sendEmail: async (p) => { calls.push(['email', p]); return { id: 'E1' } } }; const one = await dispatchDriverOfferChannels(base(store.sb), deps); const two = await dispatchDriverOfferChannels(base(store.sb), deps); assert.equal(one.sms.sent, true); assert.equal(one.email.sent, true); assert.equal(calls.length, 2); assert.equal(two.sms.reason, 'duplicate_attempt'); assert.equal(store.rows.find((r) => r.channel === 'sms').provider_message_id, 'SM1') })
test('Twilio and Resend use their REST APIs through injected fetch', async () => { env({ TWILIO_ACCOUNT_SID: 'account', TWILIO_AUTH_TOKEN: 'secret', TWILIO_FROM_NUMBER: '+18645550100', RESEND_API_KEY: 'resend-key', RESEND_FROM: 'offers@example.com' }); const calls = []; const fetch = async (url, options) => { calls.push({ url, options }); return { ok: true, json: async () => url.includes('twilio') ? { sid: 'SM1' } : { id: 'email1' } } }; assert.equal((await sendTwilioOfferSms({ to: '+18645550101', text: 'Offer' }, { fetch })).id, 'SM1'); assert.equal((await sendResendOfferEmail({ to: 'driver@example.com', subject: 'Offer', text: 'A to B' }, { fetch })).id, 'email1'); assert.match(calls[0].url, /api\.twilio\.com/); assert.equal(calls[0].options.body.get('To'), '+18645550101'); assert.equal(JSON.parse(calls[1].options.body).from, 'offers@example.com') })
test('offer channels honor opt-out, quiet hours, rate limiting, credentials, and provider errors', async () => { env({ DRIVER_OFFER_ALERT_SMS: 'send', DRIVER_OFFER_ALERT_SMS_MAX_PER_HOUR: '1' }); const store = db(); const missing = await dispatchDriverOfferChannels(base(store.sb, { prefs: { offer_sms: false } }), {}); assert.equal(missing.sms.reason, 'sms_opted_out'); const quiet = await dispatchDriverOfferChannels(base(store.sb, { offerMarker: 'quiet', suppressed: 'quiet_hours' }), {}); assert.equal(quiet.sms.reason, 'quiet_hours'); const noCreds = await dispatchDriverOfferChannels(base(store.sb, { offerMarker: 'creds' }), {}); assert.equal(noCreds.sms.reason, 'sms_provider_credentials_missing'); env({ DRIVER_OFFER_ALERT_SMS: 'send', DRIVER_OFFER_ALERT_SMS_MAX_PER_HOUR: '0', TWILIO_ACCOUNT_SID: 'a', TWILIO_AUTH_TOKEN: 'b', TWILIO_FROM_NUMBER: '+1' }); const limited = await dispatchDriverOfferChannels(base(store.sb, { offerMarker: 'limited' }), {}); assert.equal(limited.sms.reason, 'rate_limited'); process.env.DRIVER_OFFER_ALERT_SMS_MAX_PER_HOUR = '1'; const failedStore = db(); const failed = await dispatchDriverOfferChannels(base(failedStore.sb), { sendSms: async () => { throw new Error('Twilio down') } }); assert.equal(failed.sms.reason, 'provider_error'); assert.equal(failedStore.rows.find((r) => r.channel === 'sms').status, 'failed') })
test('offer channels rate limit counts only real delivery attempts, not skipped rows', async () => { env({ DRIVER_OFFER_ALERT_SMS: 'send', DRIVER_OFFER_ALERT_SMS_MAX_PER_HOUR: '1', TWILIO_ACCOUNT_SID: 'a', TWILIO_AUTH_TOKEN: 'b', TWILIO_FROM_NUMBER: '+1' }); const at = '2026-10-05T11:30:00.000Z'; const store = db([{ trip_id: 't0', driver_id: 'driver', offer_marker: 'o0', channel: 'sms', status: 'skipped', reason: 'live_send_disabled', created_at: at }, { trip_id: 't1', driver_id: 'driver', offer_marker: 'o1', channel: 'sms', status: 'skipped', reason: 'rate_limited', created_at: at }]); let sends = 0; const deps = { sendSms: async () => { sends++; return { id: 'SM' + sends } } }; const first = await dispatchDriverOfferChannels(base(store.sb, { offerMarker: 'a' }), deps); assert.equal(first.sms.sent, true); const second = await dispatchDriverOfferChannels(base(store.sb, { offerMarker: 'b' }), deps); assert.equal(second.sms.reason, 'rate_limited'); assert.equal(sends, 1) })
