/**
 * Canonical independent-contractor agreement for Clemson RIDES.
 * TEMPLATE ONLY. A licensed attorney must review this before it is used
 * with real drivers. It is not certified legal advice.
 * The SQL seed must match IC_AGREEMENT_HTML exactly.
 */

export const OPERATOR_NAME = 'Clemson RIDES / Operator'

export const IC_AGREEMENT_VERSION = 'ic-agreement-2026-09-24'

export const IC_AGREEMENT_TITLE = 'Clemson RIDES Independent Contractor Agreement'

const ARTICLES = [
  ['1. Parties and effective date', [
    `This Independent Contractor Agreement (the "Agreement") is entered into by and between ${OPERATOR_NAME} ("Platform," "Company," or "Operator") and the individual who electronically signs it ("Driver" or "Contractor"). The Company operates a technology platform under the name Clemson RIDES that connects people who request rides with independent drivers in and around Clemson, South Carolina, including trips to and from Greenville-Spartanburg International Airport (GSP), Charlotte Douglas International Airport (CLT), the Clemson University campus, downtown Clemson, and nearby communities.`,
    `This Agreement is effective on the date the Driver signs it in the driver application (the "Effective Date") and continues until it ends under the termination section. The Driver's electronic signature, the date the Driver enters, the stored signature mark, this version identifier (${IC_AGREEMENT_VERSION}), and a cryptographic hash of this text together form the execution record. If the Company publishes a later version, continued use of the Platform after notice may require a new signature. A prior signature does not amend a later version.`,
    `The Driver has had the opportunity to read this Agreement, to scroll through every section, and to decline. The Driver is not required to sign. Signing is a condition of applying to receive ride requests. Signing does not guarantee approval, trip volume, or any particular payout. An administrator must still approve the Driver before the Driver may go online or accept trips.`,
  ]],
  ['2. Definitions', [
    `"Platform" means the Clemson RIDES websites, mobile applications, dispatch tools, payment tools, and related services through which riders request transportation and drivers may choose to accept those requests. The Platform is a technology intermediary. It is not a transportation carrier, taxi company, or employer of drivers.`,
    `"Driver" or "Contractor" means the person who signs this Agreement and who, if approved, may use the Platform to offer rides. The Driver supplies the vehicle, the labor, the fuel, the insurance, the phone, and the judgment used to complete a trip. "Rider" means a person who requests a ride through the Platform. "Trip" means a single transportation engagement from an accepted pickup to a completed drop-off, including any wait time the product records. "Service Area" means Clemson, South Carolina, the Clemson University campus, Pickens County, Anderson County, and the corridors reasonably used for campus and airport trips, including GSP and CLT, as the Company may describe in the app. The Company may narrow or pause the Service Area for safety, weather, law, or operations.`,
    `"Vehicle" means the automobile the Driver registers in the application, including its make, model, color, plate, seat count, and photos. "Fees" means the platform fee, any disclosed service charge, and any adjustment the product calculates before a payout. "Confidential Information" means non-public information about riders, other drivers, trips, pricing logic, security practices, personal data, and the Company's business. "Deactivation" means suspension or removal of access to go online or accept trips. "Payout" means money the Company sends to the Driver's payout account for completed trips after fees, tips handling, and any chargeback or correction described here.`,
  ]],
  ['3. Independent contractor classification', [
    `The Driver is and shall remain an independent contractor and not an employee, agent, partner, joint venturer, or representative of the Company. Nothing in this Agreement, in the app, or in the way trips are offered creates an employment relationship, a franchise, or a partnership. The parties intend this classification under the common law of South Carolina and under the factors the Internal Revenue Service and similar agencies use to distinguish employees from independent contractors, including the absence of behavioral control, financial control, and a relationship of employment.`,
    `The Company does not control the manner or means by which the Driver drives. The Driver chooses whether to open the app, whether to go online after approval, which trips to accept, which route to drive consistent with law and the Rider's destination, when to take breaks, and when to stop driving. The Company does not set a shift, a minimum hour requirement, a quota, or a schedule. The Driver has no exclusive territory and may provide transportation services to others, including through other platforms, subject only to the narrow non-solicitation terms in this Agreement and to the safety rule that the Driver will not accept a Clemson RIDES trip the Driver cannot safely complete.`,
    `The Driver receives no salary, hourly wage, overtime, paid leave, unemployment coverage from the Company, workers' compensation coverage from the Company, health insurance, retirement benefits, or other employee benefits. The Company does not withhold income tax, Social Security, Medicare, or other payroll taxes from payouts except where a change in law compels a withholding the Company will describe in writing. The Driver is solely responsible for all taxes, estimated payments, and information returns. The Driver will complete the in-app Form W-9 and keep it accurate. The Company may issue Form 1099-NEC or another information return when required.`,
    `The Driver supplies the tools of the work: a vehicle, fuel, maintenance, a smartphone, a data plan, insurance, and any equipment the Driver chooses. The Company provides software access only. Suggestions in the app, navigation links, safety prompts, ratings, or deactivation decisions are quality and safety standards for use of the Platform. They are not day-to-day supervision of an employee. If any agency or court nonetheless claims an employment, joint-employment, or agency relationship, the Driver shall cooperate in clarifying the independent status and shall indemnify the Company for misclassification claims to the extent they arise from the Driver's conduct, representations to riders or tax authorities, or failure to follow this Agreement, to the fullest extent permitted by law.`,
  ]],
  ['4. No agency, partnership, or vicarious liability', [
    `The Driver has no authority to bind the Company, to speak for the Company, to open an account in the Company's name, to hire employees for the Company, or to accept service of process for the Company. Riders, airports, universities, law enforcement, and other third parties are not third-party beneficiaries of any promise that the Company will be vicariously liable for the Driver.`,
    `The Company is not vicariously liable for the Driver's driving, the Vehicle, the Driver's interactions with riders or the public, traffic citations, crashes, or regulatory violations. The Platform's role is to provide software that transmits a request and, when a trip completes under the product rules, to facilitate a payment. The Driver is the transportation provider for each trip the Driver accepts. No rider-facing screen, logo, or "Clemson" color scheme makes the Driver an employee or makes the Company the carrier.`,
    `The Driver shall not hold out as an employee of Clemson University, of any airport, or of the Company. Clemson University is not a party to this Agreement and does not operate the Platform. Use of the word Clemson in the product name describes the community the service is built for. It is not a representation of university sponsorship unless a separate written sponsorship says so.`,
  ]],
  ['5. Scope of services and geographic scope', [
    `If the Company approves the Driver, the Driver may use the Platform to receive ride requests in the Service Area and to accept or decline them. The Driver supplies the Vehicle and performs the transportation. The Company does not guarantee any number of requests, any fare level, any airport queue position, or any minimum earnings. Requests may be scarce or unavailable. Game days, weather, and airport conditions change demand. The Driver accepts that risk.`,
    `The Driver will transport the requesting rider and the rider's permitted guests from the agreed pickup toward the agreed drop-off, by a reasonable route, without unauthorized stops that the rider did not request, and without discrimination on any basis prohibited by applicable law. The Driver will not use the trip to solicit business for another platform, to campaign, or to create an unsafe environment. The Driver may refuse a request before acceptance. After acceptance, cancellation rules in this Agreement and in the app apply.`,
    `Airport trips, including GSP and CLT, may involve airport rules, curbside limits, and commercial-vehicle restrictions. The Driver is solely responsible for knowing and following those rules and for any fine that results from the Driver's presence or conduct. Campus trips may involve university parking and traffic rules. Those rules bind the Driver, not the Company. The Company may disable requests in a zone where operations are unsafe or unlawful.`,
  ]],
  ['6. Payment, fees, tips, deposits, chargebacks, and payouts', [
    `Rider fares are calculated by the Platform. Where the product states it, a deposit of about twenty-five percent (25%) of the quoted fare may be collected before or during the trip, and the remainder may be collected when the trip completes. The Driver is the payee of the Driver's net share. The Company retains a platform fee. Unless a specific trip screen states otherwise, the Driver's net is eighty percent (80%) of the fare amount the product uses for that split, and the Company retains twenty percent (20%). Incentives, toll reimbursements, or adjustments, if any, appear in the earnings screens and are discretionary unless a written promotion says they are guaranteed.`,
    `Tips, if riders add them through the product, are in addition to the fare split and are payable to the Driver except where a payment processor reverses them. The Company does not promise that riders will tip. The Driver will not pressure a rider to tip in cash or in the app.`,
    `Payouts are sent through the payment provider the Company uses, currently including Stripe Connect or a successor, to the account the Driver configures. Payout timing follows that provider and the Company's payout schedule, which may be delayed by review, holidays, bank processing, negative balances, or suspected fraud. Configuring payouts while an application is pending does not entitle the Driver to trip pay before approval and before completed trips exist. Empty earnings are normal before the first completed trip.`,
    `Chargebacks, refunds, payment failures, and disputed cards can reverse a fare after the Driver has been paid. The Company may debit the Driver's future payouts or connected account for the Driver's share of a reversed amount, for duplicate payments, and for incentives paid in error. The Driver will not receive a payout for a trip the Driver did not complete, for a trip canceled under the product rules, or for a trip the Company reverses because of a safety report it reasonably believes. The Company may hold a payout during an investigation of a crash, a missing-rider report, or suspected fraud. The Driver remains responsible for the costs of the trip regardless of whether the rider's payment succeeds.`,
  ]],
  ['7. Contractor bears all costs', [
    `The Driver bears all costs of being a driver. Those costs include, without limitation, federal and state income taxes, self-employment taxes, business licenses if any are required, insurance premiums, deductibles, vehicle purchase or lease payments, fuel, electricity, maintenance, tires, repairs, cleaning, phones, mobile data, mounts, chargers, tolls, parking, airport fees, traffic and parking tickets, towing, impound fees, and any expense of a crash. The Company does not reimburse those costs unless a specific in-app promotion expressly says it will, and then only up to the stated amount.`,
    `The Driver will not submit a false expense, a false mileage claim, or a request that the Company treat the Driver as an employee for benefits. If the Driver wants to track expenses for the Driver's own tax return, the Driver will do that independently. The Company's earnings screens are trip records, not a tax return and not legal or tax advice.`,
  ]],
  ['8. Assumption of risk and waiver of claims', [
    `Driving is dangerous. The Driver knowingly assumes the risk of traffic, weather, night driving, airport congestion, unruly passengers, crime, vehicle failure, and economic loss from low demand. To the fullest extent permitted by South Carolina law, the Driver waives and releases the Company and its members, managers, contractors, and agents from claims arising out of the Driver's driving, the Vehicle, a trip, a rider interaction, or the Driver's decision to go online, including claims for personal injury, property damage, lost earnings, and emotional distress, except to the extent a claim is caused by the Company's gross negligence or willful misconduct and cannot legally be waived.`,
    `The Driver waives unknown claims to the extent South Carolina law allows a waiver of claims the Driver does not yet know about. The Driver is not relying on any oral statement that driving on the Platform is safe, profitable, or supervised by the Company. If a waiver in this section is held unenforceable for a category of claim, the rest of this Agreement, including indemnification and the insurance duties, still applies.`,
  ]],
  ['9. Indemnification', [
    `The Driver shall defend, indemnify, and hold harmless the Company and its owners, managers, affiliates, agents, and service providers from and against any claim, demand, loss, damage, liability, fine, penalty, cost, and attorney's fee arising out of or related to: (a) the Driver's driving or any trip; (b) the Vehicle, including its condition, registration, or equipment; (c) injury to or death of a rider, pedestrian, or other third party, or damage to property; (d) the Driver's interaction with a rider or member of the public; (e) the Driver's violation of law, airport rule, campus rule, or this Agreement; (f) tickets, tolls, and parking; (g) the Driver's tax filings and any claim that payouts were wages, to the extent the claim is based on the Driver's conduct or representations; (h) a claim by the Driver's own insurer denying coverage because the Driver used the Vehicle for rides; (i) content the Driver uploads, including photos and signatures; and (j) the Driver's breach of confidentiality or non-disparagement.`,
    `The Company may select counsel for a covered claim at the Driver's expense, or may require the Driver to provide a defense by counsel reasonably acceptable to the Company. The Driver will not settle a claim that imposes any obligation on the Company, or that admits fault by the Company, without the Company's prior written consent. This indemnity survives termination and applies to claims filed after the Agreement ends if they arise from events during the Agreement. The indemnity is intended to be as broad as South Carolina law allows for an independent contractor and is a material reason the Company makes the Platform available.`,
  ]],
  ['10. Limitation of liability', [
    `To the fullest extent permitted by law, the Company is not liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, lost trips, or lost data, whether in contract, tort, or otherwise, even if advised of the possibility. The Company's aggregate liability arising out of this Agreement or the Platform for claims that are not validly released shall not exceed the platform fees the Company actually retained from the Driver's trips in the three (3) months before the claim, or one hundred U.S. dollars (US$100) if no such fees exist. These limits do not apply to liability that cannot be limited under applicable law, including certain claims for gross negligence or willful misconduct where a statute forbids a limit.`,
    `The Platform is provided as available. Maps, ETAs, fare quotes, and rider locations can be wrong. The Driver will not rely on the app as the sole means of navigation or as a promise that a rider will be at a pin. The Company does not warrant uninterrupted service, and maintenance, outages, or third-party failures (including Stripe, Supabase, Apple, Google, or a phone carrier) are not breaches.`,
  ]],
  ['11. Insurance', [
    `The Driver shall keep in force, at the Driver's sole expense, personal automobile liability insurance that satisfies South Carolina law and any higher limit this Agreement or a later written notice requires. Until the Company publishes a different minimum in the app, the Driver shall maintain at least the greater of (i) the statutory minimum and (ii) liability limits of $100,000 per person, $300,000 per accident for bodily injury, and $100,000 for property damage, or a combined single limit of $300,000. These figures are placeholders the Company may revise. They are not a representation that the amounts are adequate for the Driver's risk.`,
    `The Driver's policy must not exclude, and the Driver will not conceal, the Driver's use of the Vehicle to carry passengers for compensation if the policy or the law requires disclosure. The Driver will name no false garaging address. The Company may require proof of insurance, a declarations page, and notice of cancellation. Lapse of insurance is cause for immediate deactivation. The Company is not obligated to provide primary commercial coverage, occupational accident coverage, or uninsured motorist coverage for the Driver. Any coverage the Company might later buy is excess only if a policy says so, and it does not make the Driver an employee. Deductibles, exclusions, and denied claims remain the Driver's responsibility. The Driver shall notify the Company promptly of any crash on a trip.`,
  ]],
  ['12. Intellectual property and driver content', [
    `The Company owns the Platform, the Clemson RIDES name as used by the Company, the orange and purple interface, software, text, fare logic, and documentation. The Driver receives a limited, revocable, non-exclusive, non-transferable license to use the driver application while this Agreement is in effect and the Driver is allowed access. The Driver will not copy, reverse engineer, scrape, or resell the Platform, and will not use the Company's marks on a vehicle wrap or social post except as the app expressly permits.`,
    `Photos, signatures, and text the Driver submits (license images, vehicle photos, profile photos, registration images, and signature marks) remain subject to the Driver's ownership of the original where applicable, but the Driver grants the Company a worldwide, royalty-free license to host, reproduce, display to administrators, and retain those materials for safety, insurance, tax, dispute, and legal compliance, including after deactivation for as long as the Company reasonably needs them or the law requires. The Driver represents that the Driver has the right to grant that license and that profile photos are of the Driver.`,
  ]],
  ['13. Data, privacy, and telemetry', [
    `The Driver understands the app collects account data, location while the Driver is online or on a trip, device tokens, trip status, payout identifiers, document images, and signature records. Location is used to show the Driver on the map to riders when the product does so, to support safety, and to record that a trip occurred. The Driver should not go online if the Driver does not want that collection. The Company will not sell the Driver's precise trip-by-trip location as a standalone marketing product. The Company may share data with payment processors, mapping providers, insurers, background-check vendors if one is later engaged, law enforcement when required, and professional advisors.`,
    `The Driver will not export rider personal data, will not photograph a rider's identification for the Driver's own files, and will not contact a rider outside the app after a trip except as the product's lost-and-found or safety tools allow. Retention follows the Company's operational need and legal duties, including tax and safety records that may outlast the Agreement. If a privacy statute such as a state consumer-privacy law applies to a particular request, the Company will honor a verifiable request to the extent the statute requires and the data is not exempt as a safety, tax, or transaction record. This section is a plain-language description, not a complete privacy policy. The in-app privacy notice, if any, also applies.`,
  ]],
  ['14. Background checks, eligibility, and alcohol and drugs', [
    `The Driver authorizes the Company, now and while the Driver has access, to screen the Driver's identity, driving record, and criminal history to the extent the law allows, using a vendor the Company may engage later. Until a vendor is connected, the in-app authorization is stored and the background check status remains pending or submitted. A TODO remains for vendor wiring. No invented vendor key is used. Signing the in-app authorization starts that queue. It is not a representation that a report has already been pulled.`,
    `The Driver must be eligible to work in the United States and must complete the in-app eligibility attestation. The Driver will not drive if the Driver's license is expired, suspended, or revoked. The Driver will not drive under the influence of alcohol, cannabis, or any drug that impairs driving, including a prescription that makes driving unsafe. The Company may deactivate on a credible report of impairment. The Driver consents to the Company's reasonable request for an explanation after a safety incident. Refusal can be cause for deactivation. These standards exist because driving riders is safety-sensitive. They do not create a duty by the Company to supervise the Driver in real time.`,
  ]],
  ['15. Vehicle standards and documentation', [
    `The Vehicle must be the one described in the application, lawfully registered, plated, and insured, with the seat count the Driver entered, and in safe mechanical condition. The Driver will upload the registration and vehicle photos the application requires. Registration is compared to the make, model, color, and plate on the application. A mismatch is flagged and is not treated as a match. License images are always pending manual review and are never auto-approved by the app. The Driver will not submit a document that belongs to someone else.`,
    `The Driver will keep the Vehicle clean enough for a passenger, with working seatbelts for every occupied seat, legal lights, and tires with lawful tread. The Driver will not carry more passengers than the seatbelts allow or than the Vehicle record states. The Company may inspect documents, insurance proof, and, on reasonable notice, the Vehicle's visible condition at a public place in the Service Area, or may require new photos. Failure to cooperate with an audit is cause for deactivation. The Driver remains responsible for maintenance. An audit is not a certification that the Vehicle is safe.`,
  ]],
  ['16. Dispatch, acceptance, cancellation, and no-shows', [
    `A request is an offer to form a single trip, not a promise of future work. The Driver may decline. Acceptance is effective only when the Driver is approved and the Platform records the acceptance. While an application is pending review, the Driver may see trip information in the app. Offers shown before approval do not create a trip, do not assign a rider, and do not charge anyone. The Driver cannot complete acceptance or go online until an administrator sets the application to approved. Attempts to accept before approval fail.`,
    `After a real acceptance, the Driver will proceed toward the pickup without undue delay. If the Driver cancels after acceptance other than for a safety reason or a rider no-show the product recognizes, the Company may record the cancellation, reduce access, or reverse a related incentive. If the rider does not appear within the wait time the product states, the Driver may follow the in-app no-show flow. The Driver will not leave a rider in an unsafe place as a form of dispute. Fare changes mid-trip, if the product supports them, follow the product rules and are not a side agreement.`,
    `The Driver will not accept a trip and then subcontract it to another person. The Driver who accepted is the person who must drive, unless the Company has approved a different arrangement in writing. The Driver will not accept a trip the Driver cannot legally or safely complete, including when the Driver is too tired to drive.`,
  ]],
  ['17. Ratings, quality, and deactivation', [
    `Riders may rate trips. The Driver may rate riders where the product allows. Ratings are opinions used to operate the marketplace. A low rating can lead to review, coaching information in the app, or deactivation. The Company may also deactivate for safety reports, document problems, insurance lapse, fraud, abuse of riders, discrimination, repeated cancellations, or any breach. Deactivation can be immediate when safety is involved. Where practical and lawful, the Company will say that access has ended. The Company does not owe a pre-deprivation hearing unless a statute that validly applies to this non-employment relationship requires one.`,
    `The Driver may stop using the Platform at any time. Ending use does not erase ratings, trip records, tax records, or signed agreements. Reapplication after rejection or deactivation is in the Company's discretion.`,
  ]],
  ['18. Non-solicitation and limited non-competition', [
    `For twelve (12) months after the Effective Date, and continuing for six (6) months after the Driver's access ends, the Driver will not directly solicit a rider the Driver met only through the Platform to book transportation off the Platform, and will not use rider contact details from the Platform to build a competing list. This non-solicitation is limited to people and trip relationships the Driver learned through Clemson RIDES. It does not stop the Driver from driving for another company, from advertising generally, or from accepting a rider who independently finds the Driver without use of Platform data.`,
    `The Driver agrees not to operate a competing campus-and-airport dispatch product that copies the Company's non-public software or rider lists in the Service Area during the same six (6) months after access ends. General driving, including driving for nationally known rideshare services, is allowed. The Company does not seek a nationwide or perpetual ban. The parties intend this section to be no broader than South Carolina law enforces for a contractor. If a court finds a restriction too broad, the court should narrow it to the maximum enforceable scope rather than void this Agreement. The Driver agrees the limited restriction is reasonable given access to rider demand around Clemson and the airports.`,
  ]],
  ['19. Non-disparagement', [
    `The Driver will not make false or recklessly misleading public statements about the Company, its owners, its riders, or its safety record. Honest reports to law enforcement, regulators, or a tribunal, and truthful testimony under oath, are not disparagement. The Driver will not post a rider's name or a trip detail to shame a person. The Company may seek injunctive relief for a breach of this section because money damages may be inadequate. This section survives for two (2) years after termination, and longer for statements that are also defamatory or that disclose Confidential Information.`,
  ]],
  ['20. Confidentiality, publicity, and audit', [
    `The Driver will keep Confidential Information secret and will use it only to perform trips. The Driver will not screenshot rider profiles for personal storage beyond what the app retains, and will not sell trip data. The duty survives for as long as the information is not public through no fault of the Driver. The Driver will not issue a press statement implying that the Company or Clemson University employs or endorses the Driver.`,
    `The Company may audit, on reasonable notice except where fraud or safety requires speed, the Driver's insurance, registration, license status, vehicle photos, tax-form completeness (not a full tax return), and payout identity. The Driver will respond within the time the notice states. The Company may inspect a Vehicle's exterior and required safety equipment at a mutually practical public location in the Service Area. Audit rights survive for one (1) year after the last trip for records related to that trip, and longer for tax records the law requires the Driver to keep. The Company will not use an audit to direct the Driver's daily schedule.`,
  ]],
  ['21. Term, termination, and survival', [
    `This Agreement begins on the Effective Date and continues until the Driver or the Company ends it. Either party may terminate for convenience at any time, with or without cause, by stopping use or by deactivating access. The Company may also terminate for cause immediately upon breach, safety risk, insurance lapse, failed document review, fraud, or loss of legal eligibility to drive. Termination for convenience is a material term and is not a wrongful discharge. Because the Driver is not an employee, termination does not require severance, warning pay, or benefits continuation.`,
    `The following survive termination: accrued payment obligations and chargeback rights, confidentiality, indemnification, limitation of liability, assumption of risk and waivers to the extent enforceable, insurance duties for incidents during the term, intellectual-property licenses already granted, non-solicitation and the limited non-competition for their stated periods, non-disparagement, audit rights for the stated period, dispute resolution, and any other section that by its nature should survive.`,
  ]],
  ['22. Dispute resolution, arbitration, and class waiver', [
    `The parties shall first try to resolve a dispute through a written notice and a good-faith discussion for thirty (30) days. If the dispute remains, it shall be resolved by binding individual arbitration administered by the American Arbitration Association under its consumer or commercial rules, as applicable to the claim size, before a single arbitrator. The seat of arbitration is Greenville, South Carolina, or another location in the Upstate the arbitrator sets if both parties would otherwise travel unreasonably. The arbitrator may award only individual relief. Judgment on the award may be entered in a court with jurisdiction.`,
    `The Driver and the Company waive class actions, class arbitrations, and representative actions to the fullest extent permitted by law. Each will bring claims only in an individual capacity. Either party may bring an individual claim in small-claims court in Pickens County or Anderson County, South Carolina, if the claim qualifies, instead of arbitration. Either party may seek temporary injunctive relief in those courts to protect confidential information, intellectual property, or safety while arbitration proceeds. The Federal Arbitration Act governs the interpretation of this arbitration agreement. If the class waiver is held unenforceable, the class claim must proceed in court and the rest of the arbitration agreement still applies to individual claims.`,
  ]],
  ['23. Governing law and venue', [
    `This Agreement is governed by the laws of the State of South Carolina, without regard to conflict-of-law rules that would apply another state's law, except that the Federal Arbitration Act governs the arbitration agreement. Subject to arbitration, the state courts located in Pickens County or Anderson County, South Carolina, and the federal courts located in the District of South Carolina, are the exclusive venues for court proceedings. The Driver consents to personal jurisdiction there. The Driver will not argue that the forum is inconvenient solely because the Driver later moves away, provided the dispute arises from this Agreement or from trips in the Service Area.`,
  ]],
  ['24. General terms', [
    `This Agreement, including the in-app document certifications the Driver signs, is the entire agreement about its subject and supersedes oral statements and earlier contractor forms for future trips. It does not erase a trip record already created. Amendments must be in a later signed version or a written notice the product requires the Driver to accept. A failure to enforce a provision once is not a waiver. If a provision is unenforceable, the rest remains, and the unenforceable provision shall be modified to the minimum extent required to make it valid.`,
    `The Driver may not assign this Agreement. The Company may assign it to a successor that operates the Platform. Notices to the Driver may be sent to the email on the account or posted in the app and are effective when sent. Notices to the Company may be sent to the support address shown in the app. Neither party is liable for delay caused by a force majeure event outside reasonable control, including weather, pandemic orders, utility failure, or a government closure of an airport, except that payment obligations for completed trips and the Driver's safety duties during a trip already underway are not excused.`,
    `The parties are not in a special relationship of trust beyond this Agreement. Construction shall not go against the drafter solely because the Company prepared the form; the Driver could decline. Headings are for convenience. The word "including" means "including without limitation." References to days are calendar days. This Agreement may be signed in electronic counterparts.`,
  ]],
  ['25. Electronic signatures', [
    `The Driver agrees that a signature drawn in the app, together with the typed legal name and the date, is an electronic signature under the federal ESIGN Act and the South Carolina Uniform Electronic Transactions Act. It is intended to be the legal equivalent of a handwritten signature on paper. The Driver consents to receive this Agreement and related records electronically. The Company stores the version, the hash, the time, the date the Driver entered, the signature name, and the signature mark. The Driver should keep a copy. A paper copy is available by requesting it from support; requesting paper does not delay the electronic effectiveness of a signature already submitted.`,
    `By enabling the signature control only after the Driver has had a chance to scroll this Agreement, the Company records that the Driver moved through the text. The Driver remains responsible for reading it. Clicking through without reading is still assent.`,
  ]],
  ['26. Crashes, claims handling, and cooperation', [
    `If a crash, injury, or significant property loss happens on a trip, the Driver will stop when it is safe, call emergency services if anyone may be hurt, exchange the information the law requires, and notify the Company through the app or support channel as soon as the Driver can do so without interfering with first responders. The Driver will not admit that the Company is at fault, will not offer to pay a claimant on the Company's behalf, and will not give a recorded statement that purports to bind the Company. The Driver will promptly send the Company the police report number, photos the Driver is lawfully allowed to share, and the insurer claim number.`,
    `The Driver will cooperate with the Company's insurer if the Company has one for a particular loss, and with the Driver's own insurer. Cooperation includes an interview, documents, and a Vehicle inspection. Failure to cooperate can be treated as a breach and can void discretionary assistance the Company might otherwise consider. The Company has no duty to repair the Vehicle, to pay the Driver's deductible, to replace lost trip income, or to provide a substitute car. Rental cars, rides home, and medical bills are the Driver's responsibility except to the extent the Driver's own insurance or a legally mandated benefit pays them.`,
    `The Driver will preserve dash-camera footage, if any, and phone records about the trip for at least one hundred eighty (180) days, or longer if the Driver knows of a claim. Destroying that evidence after a known incident is a breach. The Company may use footage the Driver voluntarily provides to defend a claim. The Driver grants the Company permission to share that footage with counsel and insurers for that purpose.`,
  ]],
  ['27. Taxes, information returns, and no withholding', [
    `The Driver is a sole proprietor or other independent business for tax purposes unless the Driver's own advisor concludes otherwise. The Company will not withhold federal income tax, South Carolina income tax, or FICA from ordinary payouts. The Driver will make estimated payments if required and will file returns. The in-app W-9 is collected so the Company can complete information returns. A name and taxpayer identification number that do not match IRS records can trigger backup withholding if the law requires it. The Driver will correct a mismatch promptly. The Company may pause payouts until a valid certification is on file.`,
    `The Driver will not ask riders to pay the Driver's personal expenses, will not issue the Driver's own tax forms to the Company, and will not characterize the platform fee as a wage deduction. The platform fee is a charge for use of software and payment facilitation, retained before the Driver's net is calculated. Tips reported by the payment system may be included on an information return when the law requires. The Driver is responsible for the tax treatment of tips. Nothing in the earnings screen is tax advice, and the Company does not promise a particular deduction for mileage, the home office, or the phone.`,
    `If a government agency assesses the Company for taxes, contributions, or penalties because the Driver was treated as an employee, and the assessment is based on the Driver's instructions to riders, the Driver's tax filings, or the Driver's public statements that the Driver was employed by the Company, the Driver shall indemnify the Company for that assessment and the cost of responding, to the extent the law permits an indemnity of that kind. The Company will notify the Driver of a claim that seeks that indemnity and will allow the Driver to participate with the Driver's own counsel, without limiting the Company's control of its own defense.`,
  ]],
  ['28. Rider interactions, discrimination, and removal from a trip', [
    `The Driver will treat riders and the public with ordinary courtesy and will not refuse a trip, or drop a rider mid-trip, because of race, color, religion, sex, national origin, disability, or another characteristic protected by applicable public-accommodation or transportation law. A refusal based on a genuine safety threat, a vehicle seat limit, a pet the Driver's listing does not accept, or an unlawful request is not discrimination. The Driver will allow a service animal that the law requires the Driver to transport, even if the Driver dislikes animals, unless a legally recognized exception applies and the Driver can state it calmly.`,
    `The Driver will not touch a rider except as reasonably needed to assist with a mobility device the rider asks for help with, will not comment on a rider's body or relationships, and will not ask a rider for a social contact. Harassment is cause for immediate deactivation. If a rider is threatening, the Driver may end the trip in a safe public place and contact law enforcement. The Driver will use the in-app safety tools when they exist. The Company does not promise a particular response time from support during a live incident. Calling 911 is the Driver's responsibility when there is danger.`,
    `The Driver will not carry a weapon in the Vehicle if doing so is unlawful, and will follow any stricter rule the Company posts for rider safety. The Driver will not use a trip to transport contraband, to evade law enforcement, or to move a person who is seeking help committing a crime. The Driver will not leave the Vehicle unattended with a rider's property in a way that invites theft, and will use the lost-and-found flow rather than keeping found items.`,
  ]],
  ['29. Records, setoff, and negative balances', [
    `The Company may keep trip records, document images, signature records, payout identifiers, and audit results for as long as it reasonably needs them for safety, tax, insurance, and disputes, and for as long as a statute requires. The Driver may request a copy of the signed Agreement. The Company may decline to export another person's personal data. The Driver will keep the Driver's own copies of insurance and tax filings. The Company's records control if they conflict with the Driver's memory about whether a trip was accepted or what the fare split was, unless the Driver shows a clear system error.`,
    `The Company may set off against future payouts any amount the Driver owes under this Agreement, including chargebacks, incentives paid in error, damage the Driver agrees in writing to repay, and the Company's reasonable out-of-pocket cost of a claim the Driver was obligated to defend and did not. A negative balance does not by itself create a consumer loan. If the Driver's connected account cannot cover a negative balance, the Driver will pay the Company within thirty (30) days of written notice. The Company may deactivate access until the balance is cured. Setoff is in addition to indemnification, not a limit on it.`,
  ]],
  ['30. Representations the Driver makes on signing', [
    `The Driver represents that: the Driver is at least the age required to drive for compensation in South Carolina; the driver's license the Driver will show is genuine and belongs to the Driver; the Driver is eligible to work in the United States; the Vehicle is lawfully in the Driver's possession and may be used to carry paying passengers to the extent the Driver's insurance and the law require; the insurance described in this Agreement is in force or will be in force before the Driver goes online; the photos and registration the Driver submits are accurate; the Driver has read this Agreement; and the Driver is not relying on any promise of earnings, hours, or employment.`,
    `The Driver will update the Company promptly if a representation stops being true, including a license suspension, an insurance cancellation, a change of the Vehicle, or a loss of work eligibility. Continuing to go online after a representation fails is a material breach. The Company may rely on the Driver's representations without independent investigation, and any review the Company does perform is for the Company's protection, not a duty of care owed to the Driver or to riders. Approval of an application means only that the Company is willing to allow access on these terms. It is not a certification to the public that the Driver is safe, insured, or competent.`,
  ]],
  ['31. Injunctive relief and remedies', [
    `A breach of confidentiality, intellectual-property restrictions, non-solicitation of riders learned through the Platform, or non-disparagement may cause harm that money cannot fully repair. The Company may seek a temporary restraining order, preliminary injunction, or other equitable relief in the courts identified in this Agreement, without the necessity of proving actual damages or posting a bond to the extent a court may waive a bond. Equitable relief is in addition to arbitration of claims for damages, not a waiver of arbitration. The Driver agrees that the Company would be immediately and irreparably harmed by misuse of rider contact data or by a public statement that riders should stop using the Platform because of a false safety claim.`,
    `Except where this Agreement provides a different rule, each party bears its own attorney's fees. If the Company is the prevailing party in a proceeding to enforce indemnification, confidentiality, or an injunction, the Driver shall pay the Company's reasonable attorney's fees and costs. If a statute awards fees to a prevailing consumer and that statute validly applies despite this independent-contractor relationship, the statute controls for that claim only.`,
  ]],
  ['32. Operations around Clemson, airports, and events', [
    `The Service Area includes ordinary campus trips among academic buildings, residence areas, downtown Clemson, and nearby apartments, and longer trips to GSP and, when offered, CLT. On university event days, including home football games, demand and traffic change. The Driver decides whether to drive. The Company may show event information and may apply a fare adjustment the product discloses. An event surge, if any, is a pricing output of the software, not a shift assignment and not a promise that the Driver will be busy. The Driver will follow law enforcement direction around the stadium even if the app's pin points somewhere else. The Driver will not block a fire lane, a tunnel, or an airport commercial lane to wait for a ping.`,
    `The Driver will not pick up or drop off where a sign, officer, or airport rule forbids it, even if a rider asks. If a rider insists on an unlawful stop, the Driver may refuse or reroute to the nearest lawful point and should record the reason in the app if a field exists. The Driver is responsible for parking fees the Driver chooses to incur. Tolls the product does not reimburse stay with the Driver. The Driver will not ask a rider to pay the Driver's toll in cash as a condition of finishing a trip that the fare already covers under the product rules.`,
    `Night driving, rain, and rural roads between Clemson and the airports are part of the assumed risk. The Driver will not accept an airport trip if the Driver is too tired, if the Vehicle is unsafe in the weather, or if the Driver's insurance would not cover the trip. The Company does not monitor the Driver's hours and does not promise a fatigue-management program. The Driver is the person who decides the Driver is fit. A later claim that the Company should have taken the Driver offline does not shift that decision.`,
    `The Driver will keep the phone mounted or otherwise used in a way that complies with South Carolina distracted-driving law. The Driver will not text with a rider while the Vehicle is moving except as a hands-free action the law allows. Navigation may be opened from the app into Apple Maps or Google Maps. Those services are third parties. A wrong route is not the Company's breach. The Driver still chooses the path that can be driven lawfully.`,
  ]],
  ['33. Signature blocks', [
    `PLATFORM / COMPANY: ${OPERATOR_NAME}. The Company accepts this Agreement when it makes the signature step available and stores the Driver's completed signature record against this version. No separate wet-ink signature by the Company is required.`,
    `DRIVER: The person named in the signature field below, who confirms: I have scrolled this Agreement; I am an independent contractor and not an employee; I will bear my own costs, taxes, and insurance; I will defend and indemnify the Company as this Agreement states; I understand I cannot accept rides until an administrator approves me; and I intend my in-app signature and the date I enter to bind me.`,
    `This document is a product template for counsel to review before production use with real drivers. It is not a statement that an attorney has certified it, and it is not legal advice to the Driver. The Driver should consult the Driver's own advisor about taxes, insurance, and classification.`,
  ]],
]

function paragraph(text) {
  return `<p>${text}</p>`
}

export const IC_AGREEMENT_HTML = [
  `<h1>${IC_AGREEMENT_TITLE}</h1>`,
  `<p>Version ${IC_AGREEMENT_VERSION}. Parties: the Driver and ${OPERATOR_NAME}.</p>`,
  ...ARTICLES.flatMap(([title, paragraphs]) => [
    `<h2>${title}</h2>`,
    ...paragraphs.map(paragraph),
  ]),
].join('')

export function agreementPlainParagraphs() {
  return ARTICLES.flatMap(([, paragraphs]) => paragraphs)
}
